apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.backend.port }}"
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
            - name: POSTGRES_DB
              value: {{ .Values.database.dbname }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: DATABASE_URL
              value: {{ .Values.database.serviceName }}
            - name: ConnectionStrings__DefaultConnection
              value: {{ printf "Host=%s;Port=%v;Database=%s;Username=%s;Password=%s;Pooling=%t;Include Error Detail=%t;"
              .Values.database.host
              .Values.database.port
              .Values.database.dbname
              .Values.database.user
              .Values.database.password
              .Values.database.pooling
              .Values.database.includeErrorDetail | quote }}
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.backend.environment }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
spec:
  selector:
    app: {{ .Values.backend.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }} # The port exposed in the cluster
      targetPort: {{ .Values.backend.port }} # The port inside the backend container
  type: ClusterIP # 👈 Only accessible inside the cluster
