frontend:
  image: ghcr.io/efficient-and-fun/plananaz-frontend-image
  tag: 77e39b668f0c4a4076bcfd789964b15748dd6fea
  pullPolicy: Always
  port: 80
  VITE_API_BASE_URL: "http://backend:5246"
  serviceName: frontend

backend:
  image: ghcr.io/efficient-and-fun/plananaz-backend-image
  tag: 32dd212450561a732c6536f895bbef5911beb2f4
  port: 5246
  serviceName: backend
  environment: "Development"

database:
  host: database
  image: postgres
  pullPolicy: IfNotPresent
  tag: 16
  port: 5432
  user: plananaz
  password: plananaz-secret
  dbname: plananaz
  serviceName: database
  pooling: true
  includeErrorDetail: true
  forceInitJob: false

storage:
  enabled: true
  storageClassName: cinder-csi
  size: 5Gi
  hostPath: "/mnt/data/db"


service:
  frontendPort: 8080
  backendPort: 5246
  databasePort: 5432
  type: ClusterIPs

ingress:
  enabled: true
  defaultHost: plananaz.pm4.init-lab.ch