name: Update Values File

on:
  workflow_dispatch:
    inputs:
      latestSHA:
        description: 'Latest commit SHA from app repo'
        required: true
        type: string

jobs:
  update-values:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Update values.yaml
        run: |
          echo "Before:"
          cat plananaz/values.yaml

          sed -i '/^backend:/,/^[^[:space:]]/ s/^\(\s*tag:\s*\).*/\1${{ github.event.inputs.latestSHA }}/' plananaz/values.yaml

          echo "After:"
          cat plananaz/values.yaml


      - name: Commit and push changes
        run: |
          run: |
          git config --global user.name "Michael Weinhold"
          git config --global user.email "miweinho@users.noreply.github.com"
          git commit -am "update image tag ${{inputs.latestSHA}}"
          git push
          
